language: python
sudo: false
python:
    - "2.7"

install:
    - pip install .
    - pip install flake8

script:
    - flake8 jsoncsv tests --max-line-length=200
    - nosetests --cover-package=jsoncsv --with-coverage
    - python setup.py install
    - cat fixture/expand.json|jsoncsv -e --safe
