language: python
sudo: false
python:
    - "2.7"

install:
    - pip install .
    - pip install flake8
    - pip install coverage
    - pip install coveralls

script:
    - flake8 jsoncsv tests --max-line-length=200
    - nosetests --cover-package=jsoncsv --with-coverage
    - python setup.py install
    - cat fixture/raw.json|jsoncsv -e > fixture/expand.test.json && diff fixture/expand.json fixture/expand.test.json

after_success:
  - coveralls
