language: python
cache: pip
sudo: false
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install .
    - pip install flake8
    - pip install coverage
    - pip install coveralls
script:
    - flake8 jsoncsv tests --max-line-length=200
    - nosetests --cover-package=jsoncsv --with-coverage
    - python setup.py install
    - cat fixture/files/raw.0.json|jsoncsv -e > fixture/files/tmp.expand.0.json
    - cat fixture/files/raw.0.json|jsoncsv -e|jsoncsv -r|jsoncsv > fixture/files/tmp.expand.0.json
    - cat fixture/files/expand.2.json|jsoncsv|mkexcel -t xls > fixture/files/tmp.output.2.xls
    - cat fixture/files/expand.2.json|jsoncsv|mkexcel -t csv > fixture/files/tmp.output.2.csv
    - cat fixture/files/raw.1.json|jsoncsv -A|mkexcel > fixture/files/tmp.output.1.csv
    - cat fixture/files/raw.1.json|jsoncsv --array|mkexcel > fixture/files/tmp.output.1.csv
after_success:
    - coveralls
notifications:
    email: false
